name: postgis_docker

services:
  postgis:
    image: kartoza/postgis:16-3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=bike_monitor
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5433:5432
    restart: on-failure
